"""open-compute: a model-agnostic computer-use core.

A small, dependency-light core for building computer-use agents that can run
Claude *and* OpenAI computer-use (and a mock) behind one interface, with a
hybrid perception layer, normalized coordinates, a canonical action schema, and
a central safety gate.

Importing this package never requires a vendor SDK -- the ``anthropic`` and
``openai`` packages are imported lazily, only when their concrete backend is
instantiated. The default wiring (mock backend + mock executor) runs fully
offline.

Quick start::

    from open_compute import AgentLoop, Config

    loop = AgentLoop(Config(backend="mock"))
    result = loop.run("Open the settings page and enable dark mode")
    print(result.done, result.steps)
"""

from __future__ import annotations

from .actions import Action, ActionType, to_claude, to_openai
from .backends import BackendResult, ComputerBackend, MockBackend, get_backend
from .config import Config
from .cooperative import (
    CooperativeOrchestrator,
    HashChainAudit,
    InstructionOrigin,
    LatchedEmergencyStop,
    ObservationDigest,
    WorkflowOutcome,
    WorkflowPlan,
)
from .coordinates import denormalize, normalize, rescale
from .drivers import Executor, MockExecutor, SemanticBrowserDriver
from .human_activity import (
    GetLastInputInfoAdapter,
    HumanActivityClassifier,
    InputProvenance,
    LastInputSample,
)
from .loop import AgentLoop, LoopResult, StepTrace
from .perception import Observation, PerceptionProvider, ScreenshotPerception
from .safety import Decision, PolicyResult, SafetyPolicy
from .virtual_pointer import (
    PointerAuditPort,
    PointerAuditStamp,
    PointerAuthorization,
    PointerButton,
    PointerCoordinateFrame,
    PointerDispatchKind,
    PointerFrameKind,
    PointerOrigin,
    PointerOwnershipPort,
    PointerPhase,
    PointerPosition,
    PointerProvenance,
    PointerReceipt,
    PointerSessionPort,
    PointerSourceState,
    PointerTransition,
    PointerTransitionRequest,
    VirtualPointerCore,
)
from .virtual_pointer_overlay import (
    CallbackPointerOverlayRenderer,
    ModelPointerFrame,
    PngPointerCaptureProjector,
    PointerCaptureAudit,
    PointerCaptureBundle,
    PointerOverlayCapabilities,
    PointerOverlayCommand,
    PointerOverlayContractError,
    PointerOverlayRenderer,
    PointerOverlayShape,
    PointerOverlayStyle,
    PointerProjectionError,
    PointerRenderSurface,
    RawPointerCapture,
    VirtualPointerOverlayController,
)
from .virtual_pointer_windows import (
    CtypesWindowsPointerWindowHost,
    CtypesWindowsVirtualDesktopProbe,
    WindowsPointerSurfaceTracker,
    WindowsPointerWindowHost,
    WindowsPointerWindowSpec,
    WindowsVirtualDesktopProbe,
    WindowsVirtualDesktopSnapshot,
    WindowsVirtualPointerOverlayRenderer,
    pointer_window_spec,
    surface_matches_command,
)
from .virtual_target import (
    BrowserDriverSemanticAdapter,
    CallbackSemanticTargetAdapter,
    RegistryObservationSnapshot,
    RegistrySemanticObservationPort,
    SemanticActivationAuthorization,
    SemanticActivationReceipt,
    SemanticActivationRequest,
    SemanticDispatchOutcome,
    SemanticFocusSnapshot,
    SemanticObservation,
    SemanticResolutionStatus,
    SemanticResolvedTarget,
    SemanticTargetIdentity,
    SemanticTargetResolution,
    SemanticTargetState,
    SemanticVerification,
    SemanticWindowBinding,
    UiaTargeterSemanticAdapter,
    VirtualTargetActivationCore,
    pointer_frame_record,
    uia_target_stable_id,
)
from .virtual_injection import (
    ClassifiedHumanActivityAdapter,
    ControlSessionInjectionAdapter,
    DpiFrameEvidence,
    InjectionAuthorization,
    InjectionAuditPort,
    InjectionFailure,
    InjectionObservation,
    InjectionPermit,
    InjectionPolicy,
    InjectionVerification,
    InputSecurityEvidence,
    NativeInjectionOutcome,
    NativeMousePacket,
    PreclickEvidence,
    VirtualInjectionFallback,
    VirtualInjectionReceipt,
    VirtualInjectionRequest,
    WindowProbePreclickAdapter,
    WindowsInputSecurityProbe,
    WindowsSendInputHostAdapter,
    injection_request_fingerprint,
)

__version__ = "0.9.0"

__all__ = [
    "Action",
    "ActionType",
    "to_claude",
    "to_openai",
    "Config",
    "CooperativeOrchestrator",
    "HashChainAudit",
    "InstructionOrigin",
    "LatchedEmergencyStop",
    "ObservationDigest",
    "WorkflowOutcome",
    "WorkflowPlan",
    "GetLastInputInfoAdapter",
    "HumanActivityClassifier",
    "InputProvenance",
    "LastInputSample",
    "normalize",
    "denormalize",
    "rescale",
    "Observation",
    "PerceptionProvider",
    "ScreenshotPerception",
    "SafetyPolicy",
    "PolicyResult",
    "Decision",
    "Executor",
    "SemanticBrowserDriver",
    "MockExecutor",
    "ComputerBackend",
    "BackendResult",
    "MockBackend",
    "get_backend",
    "AgentLoop",
    "LoopResult",
    "StepTrace",
    "PointerAuditPort",
    "PointerAuditStamp",
    "PointerAuthorization",
    "PointerButton",
    "PointerCoordinateFrame",
    "PointerDispatchKind",
    "PointerFrameKind",
    "PointerOrigin",
    "PointerOwnershipPort",
    "PointerPhase",
    "PointerPosition",
    "PointerProvenance",
    "PointerReceipt",
    "PointerSessionPort",
    "PointerSourceState",
    "PointerTransition",
    "PointerTransitionRequest",
    "VirtualPointerCore",
    "CallbackPointerOverlayRenderer",
    "ModelPointerFrame",
    "PngPointerCaptureProjector",
    "PointerCaptureAudit",
    "PointerCaptureBundle",
    "PointerOverlayCapabilities",
    "PointerOverlayCommand",
    "PointerOverlayContractError",
    "PointerOverlayRenderer",
    "PointerOverlayShape",
    "PointerOverlayStyle",
    "PointerProjectionError",
    "PointerRenderSurface",
    "RawPointerCapture",
    "VirtualPointerOverlayController",
    "CtypesWindowsPointerWindowHost",
    "CtypesWindowsVirtualDesktopProbe",
    "WindowsPointerSurfaceTracker",
    "WindowsPointerWindowHost",
    "WindowsPointerWindowSpec",
    "WindowsVirtualDesktopProbe",
    "WindowsVirtualDesktopSnapshot",
    "WindowsVirtualPointerOverlayRenderer",
    "pointer_window_spec",
    "surface_matches_command",
    "CallbackSemanticTargetAdapter",
    "BrowserDriverSemanticAdapter",
    "RegistryObservationSnapshot",
    "RegistrySemanticObservationPort",
    "SemanticActivationAuthorization",
    "SemanticActivationReceipt",
    "SemanticActivationRequest",
    "SemanticDispatchOutcome",
    "SemanticFocusSnapshot",
    "SemanticObservation",
    "SemanticResolutionStatus",
    "SemanticResolvedTarget",
    "SemanticTargetIdentity",
    "SemanticTargetResolution",
    "SemanticTargetState",
    "SemanticVerification",
    "SemanticWindowBinding",
    "UiaTargeterSemanticAdapter",
    "VirtualTargetActivationCore",
    "pointer_frame_record",
    "uia_target_stable_id",
    "ClassifiedHumanActivityAdapter",
    "ControlSessionInjectionAdapter",
    "DpiFrameEvidence",
    "InjectionAuthorization",
    "InjectionAuditPort",
    "InjectionFailure",
    "InjectionObservation",
    "InjectionPermit",
    "InjectionPolicy",
    "InjectionVerification",
    "InputSecurityEvidence",
    "NativeInjectionOutcome",
    "NativeMousePacket",
    "PreclickEvidence",
    "VirtualInjectionFallback",
    "VirtualInjectionReceipt",
    "VirtualInjectionRequest",
    "WindowProbePreclickAdapter",
    "WindowsInputSecurityProbe",
    "WindowsSendInputHostAdapter",
    "injection_request_fingerprint",
    "__version__",
]
